project:
  type: website
  output-dir: docs
  
  
website:
  title: "Biostatistics"
  sidebar:
    style: "floating"
    search: true
    contents:
      - W1_Intro.qmd
      - W1b_IntroR.qmd
      - W2_Models.qmd
      - W3_DataWranglingR.qmd
      - W4_DataVizR.qmd
      - W5_Sampling.qmd
      - W6_ProbabilityR.qmd
      - W7_Hypothesis.qmd
      - W8_ModelingRelationships.qmd
      - W9_FirstAnalysisR.qmd
      - W10_GLM.qmd
      - W11_GLMinR.qmd
      - W12_LMM.qmd
      - W15_RepResearchR.qmd

format:
  html:
    theme: cosmo
  
